### ISSUE TITLE
Users created by DB_USERS cannot query views

### ISSUE THREAD

**Issue by agross** [nafets227/finance#12]
I create a `query` use to read transactions and balances. The user is only able to access `fn_entry`, but not views like `fn_entry_balance`.

**Comment by nafets227** [comment]
Can you post (part of) the Log?
the interesting part should look like this:

> Got DBADM privilege because $MYSQL_ROOT_PASSWORD is set.
> Granting DB privileges to finance.
> + set +x
> Creating DB Role fin_user.
> Creating DB User stefan with password
> Creating/Updating database dbFinance.
> ---------- aqhbci-tool4 listusers

**Comment by agross** [comment]
```
Setting permissions of /finance
chown: changing ownership of '/finance/.hbci-pinfile': Read-only file system
chown: changing group of '/finance/.hbci-pinfile': Read-only file system
chmod: changing permissions of '/finance/.hbci-pinfile': Read-only file system
chmod: changing permissions of '/finance/.hbci-pinfile': Read-only file system
Switching to restricted user finance
PING db (172.26.0.2) 56(84) bytes of data.
64 bytes from banking_db_1.banking_default (172.26.0.2): icmp_seq=1 ttl=64 time=0.122 ms
--- db ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.122/0.122/0.122/0.000 ms
Got DBADM privilege because $MYSQL_ROOT_PASSWORD is set.
Granting DB privileges to finance.
Creating DB Role fin_user.
Creating DB User query with password
Creating/Updating database finance.
```

**Comment by nafets227** [comment]
Strange, could not reproduce it here. Can you try a different username, just to be sure "query" is not creating confusion in any SQL syntax?
Did you test it on an empty DB?

**Comment by agross** [comment]
Sorry, this has been a false positive caused by Sequel Pro. I can run queries just fine. When selecting a view, Sequel Pro likes to execute `SHOW VIEW` on behalf of `query`, which errors out.
