### ISSUE TITLE
Issues with "E" bookings for Sparkasse

### ISSUE THREAD

**Issue by agross** [nafets227/finance#16]
Hello,

I have a new account with Sparkassse, and it appears that the balance calculation is different compared to other accounts. All other accounts work fine.

The latest import shows the following for the account in question:

```
Apr 13 10:00:43 router docker[1725740]: BuchIgn(900): 86055592/1090292784 2022-03-31 E   75.97
Apr 13 10:00:43 router docker[1725740]: BuchIgn(900): 86055592/1090292784 2022-04-01 E   75.76
Apr 13 10:00:43 router docker[1725740]: BuchIgn(900): 86055592/1090292784 2022-04-06 E   65.76
Apr 13 10:00:43 router docker[1725740]: BuchIgn(900): 86055592/1090292784 2022-04-07 E   36.76
Apr 13 10:00:43 router docker[1725740]: BuchIgn(900): 86055592/1090292784 2022-04-11 E   36.29
```

The last balance as of 2022-04-11 is `36,29`. The latest `"E"` bookings in the database look like this:

```tsv
"1090292784"	"86055592"	"2022-03-31"	"EUR"	"75.97"
"1090292784"	"86055592"	"2022-04-01"	"EUR"	"75.76"
"1090292784"	"86055592"	"2022-04-04"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-05"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-06"	"EUR"	"65.76"
"1090292784"	"86055592"	"2022-04-07"	"EUR"	"36.76"
"1090292784"	"86055592"	"2022-04-08"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-09"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-10"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-11"	"EUR"	"36.48"
"1090292784"	"86055592"	"2022-04-11"	"EUR"	"36.29"
"1090292784"	"86055592"	"2022-04-11"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-12"	"EUR"	"0.00"
"1090292784"	"86055592"	"2022-04-13"	"EUR"	"0.00"
```

The interleaved `"0.00"` entries are due to days without balance changes. My other accounts do not show this behavior.

My goal is to get the account's balance, which I did until now by querying the newest `"E"` entry of `fn_entry`.

**Comment by nafets227** [comment]
Can you please check the logs if there is any BuchIgn or BuchOK with "E" or "A" for the relevant days?
finance does not invent any bookings, it only stores what aqbanking gives to it (and aqbanking only takes what it gets from the bank).

A possible workaround could be to delete all 0 EUR bookings, but this would mean to also deleted "real" 0 EUR bookings or balances.

**Comment by agross** [comment]
> Can you please check the logs if there is any BuchIgn or BuchOK with "E" or "A" for the relevant days?

This is interesting:

```
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-04-15 E       0.00
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-03-25 E    49.99
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-03-28 E    50.01
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-03-30 E   35.77
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-03-31 E   75.97
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-04-01 E   75.76
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-04-06 E   65.76
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-04-07 E   36.76
Apr 15 18:03:34 router docker[3153017]: BuchIgn(900): 86055592/1090292984 2022-04-11 E   36.29
```

Note the first line. It's the newest entry, but it comes first.

The "store file" related to these looks like this:

```
   balanceList {
        balance {
          char date="20220415"
          char value="3629%2F100%3AEUR"
          char type="booked"
        } #balance

        balance {
          char date="20220415"
          char value="0%3AEUR"
          char type="noted"
        } #balance

        balance {
          char date="20220325"
          char value="4999%2F100%3AEUR"
          char type="noted"
        } #balance

        balance {
          char date="20220328"
          char value="5001%2F100%3AEUR"
          char type="noted"
        } #balance

# ... more stuff
```

For today (April 15) there are two entries, the bogus "noted" one, and a "booked" entry that reflects the actual account balance.

**Comment by nafets227** [comment]
checking the source code (fntxt2sql/fntxt2sql-aqb-bal.c) I found that, for every day, either noted or booked is used, whatever is non zero. If both are zero, then zero is used.

Maybe I need to add a specific workaround or option for your bank, that seams to deliver wrong data in noted fields.

If you feel comfortable I am more than willing to accept a pull request. Otherwise I can put it on my list, but it will take some weeks or even months due to other prioritized parallel projects and the fact that I am doing this in my private life only.

**Comment by agross** [comment]
> either noted or booked is used, whatever is non zero. 
> Maybe I need to add a specific workaround 

That doesn't sound like a specific workaround, but rather the way it should be implemented, right? It's definitely the case here.

> If you feel comfortable I am more than willing to accept a pull request.

Can you point me to the location where you would put the new code?

**Comment by nafets227** [comment]
I'd add a specific option, lets say "-aqbBookedBalance" in fntxt2sql.c (function main)
store the option in the config struct that needs to be extended

then in fntxt2sql-aqb-bal.c line 94ff honor this option.
If the option is not set, everything should work as up to now.
If the option is set, only take the "booked" balances.

Not clear to me yet, if we can at this point distinguish between a "real" 0 and a dummy 0 just created by the output, e.g. because there is a noted balance for that day without a booked balance. Probably it needs cross testing also with other banks.

**Comment by nafets227** [comment]
just fell over this myself, my Bank (HypoVereinsbank) show the same weird data for today's balances.
Unfortunately I pointed to the wrong source, in reality fntxt2sql-aqb6.c contains the right source, and it simply ignores "booked" balances (Line 115).

With my bank the data seems wrong for the current day, only valid the day after and it changes also :( No glue yet how to handle this correctly.

**Comment by nafets227** [comment]
Checking the example above and the results of my banks (HVB, Sparkasse, ING) I propose the following rule:
1. If both noted and booked values are present, ignore the balance if this day.
Its because this is the current day and balances are not final, so they can change in the remaining hours of the day.
2. Otherwise, take booked or notes balance, whatever is present.

@agross Do you think this could solve also your issue?
If yes, I'll try to code it next days and release a new version.

**Comment by agross** [comment]
To be honest I do not know whether it will solve my issue. I certainly hope it will. I'm happy to test any changes that you propose (by replacing the currently used docker image).

**Comment by nafets227** [comment]
@agross please try ghcr.io/nafets227/finance:local

Remember its a development release, so I strongly suggest to not use it with your production data (although I don't expect it to harm them).
It should fix the balance issue for all newly read balances, data from the past (=already in the DB) will not be corrected.

Happily waiting for your feedback, available for any questions or help.

**Comment by agross** [comment]
FYI, I'm currently testing the image.

While looking at the logs I found this:

```
/usr/local/bin/finance-entrypoint: line 668: MAIL_TO: unbound variable
```

Which makes the container exit with status `1`. Probably the entrypoint script needs to check if the variable is bound before accessing it (`[[ -v MAIL_TO ]]`) or substitute the value if unset.

**Comment by nafets227** [comment]
thanks for reporting the issue of unbound MAIL_TO, will fix it.
But this is at the end of the procedure, so database should already have been updated and you can keep testing.

**Comment by agross** [comment]
OK, thank you.

After running the container I tried my "unpatched" query to get all account's balances:

```sql
SELECT *
FROM (
SELECT e.ORIG_KTONR,
       e.ORIG_BLZ,
       e.DATUM,
       e.WAEHRUNG,
       e.BETRAG,
       RANK() OVER (PARTITION BY e.ORIG_KTONR, e.ORIG_BLZ ORDER BY e.ID DESC) AS rank
FROM fn_entry AS e
WHERE BUCHART = 'E'
) AS x
WHERE rank <= 1
```

It returns `0` for the account in question.

The "patched" query is this one:

```sql
SELECT *
FROM (
SELECT e.ORIG_KTONR,
      e.ORIG_BLZ,
      e.DATUM,
      e.WAEHRUNG,
      e.BETRAG,
      RANK() OVER (PARTITION BY e.ORIG_KTONR, e.ORIG_BLZ ORDER BY e.ID DESC) AS rank
FROM fn_entry AS e
WHERE BUCHART = 'E' AND
      BETRAG != 0
) AS x
WHERE rank <= 1
```

It returns the correct balance (which is `> 0`).

**Comment by agross** [comment]
In case you wonder why I use this query instead of `fn_entry_balance` (I think we had a discussion on this already). The values of this table don't make sense to me. For this September it's negative. And summing up an account's rows doesn't yield the actual balance.

**Comment by agross** [comment]
Scratch the above. The update didn’t go through, so the container didn't have a chance to import new bookings.

**Comment by agross** [comment]
The results of the patched and the unpatched query are now the same. I consider that to be good news ;-)

**Comment by nafets227** [comment]
Thank you! sounds great!

just pushed a fix on unset MAIL_TO.
I´ll publish a new version with both fixes today or tomorrow.

fn_entry_balance is definitely something I should be looking at, it does not look like its doing what it should do.

**Comment by agross** [comment]
Thank you for providing a fix! Seems like my C skills have become too rusty and the patched query was an okay workaround for me ;-)
