### ISSUE TITLE
Container does not start with unset `MYSQL_ROOT_PASSWORD`

### ISSUE THREAD

**Issue by agross** [nafets227/finance#35]
```
/usr/local/bin/finance-entrypoint: line 616: MYSQL_ROOT_PASSWORD: unbound variable
```

**Comment by agross** [comment]
If it's empty the container starts.

The "root pw provided?" test could use `-v` in addition `-z` or provide an empty default if the var is unset.

**Comment by agross** [comment]
1.0.1

**Comment by agross** [comment]
This is the environment block of the container that exposes the error in the OP. Since the MariaDB image no longer supports `MYSQL_*` env vars you see quite a bit of duplication.

```json
"Env": [
        "MARIADB_ROOT_PASSWORD=secret",
        "MYSQL_USER=finance",
        "MARIADB_USER=finance",
        "MYSQL_PASSWORD=secret",
        "MARIADB_PASSWORD=secret",
        "MYSQL_DATABASE=finance",
        "MARIADB_DATABASE=finance",
        "MARIADB_AUTO_UPGRADE=true",
        "MARIADB_DISABLE_UPGRADE_BACKUP=true",
        "MYSQL_HOST=db",
        "DB_USERS=query",
        "DB_query_PASSWORD=secret",
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ],
```

**Comment by nafets227** [comment]
Fixed in the branch no-mysqlroot_pw.
Due to internal GitHub action issues, no docker image can be pushed at the moment.

Do you have the chance to test anyhow?
Just checkout the repo and exec docker build -t mytestimage.

**Comment by agross** [comment]
LGTM! Thanks!
